/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com_cliente_servidor.vistaC;


import com_cliente_servidor.controladorC.ControladorCliente;
import com_cliente_servidor.modeloC.Cliente;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.jshell.SourceCodeAnalysis;

/**
 *
 * @author raulr
 */

public class ClienteFrame extends javax.swing.JFrame implements VistaC{
    
    ControladorCliente controlador;
    /**
     * Creates new form ServidorFrame
     */
    public ClienteFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensajes_Cliente = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mensajes_Cliente2 = new javax.swing.JTextArea();
        Cliente_Label = new javax.swing.JLabel();
        Consumir_Button = new javax.swing.JButton();
        jButtonsocket = new javax.swing.JButton();
        JButton_Refresh = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(900, 600, 600, 600));
        setPreferredSize(new java.awt.Dimension(900, 568));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensajes_Cliente.setEditable(false);
        Mensajes_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        Mensajes_Cliente.setColumns(20);
        Mensajes_Cliente.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        Mensajes_Cliente.setRows(5);
        jScrollPane1.setViewportView(Mensajes_Cliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 338));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 420, 360));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensajes_Cliente2.setEditable(false);
        Mensajes_Cliente2.setColumns(20);
        Mensajes_Cliente2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        Mensajes_Cliente2.setRows(5);
        jScrollPane2.setViewportView(Mensajes_Cliente2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 340));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 440, 360));

        Cliente_Label.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        Cliente_Label.setText("CLIENTE");
        jPanel1.add(Cliente_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        Consumir_Button.setBackground(new java.awt.Color(74, 168, 211));
        Consumir_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Consumir_Button.setText("Consumir Paquete");
        Consumir_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consumir_ButtonMouseClicked(evt);
            }
        });
        Consumir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consumir_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Consumir_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 190, 40));

        jButtonsocket.setBackground(new java.awt.Color(166, 117, 179));
        jButtonsocket.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jButtonsocket.setText("Cerrar Socket");
        jButtonsocket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsocketMouseClicked(evt);
            }
        });
        jButtonsocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsocketActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsocket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 310, 50));

        JButton_Refresh.setBackground(new java.awt.Color(74, 168, 211));
        JButton_Refresh.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        JButton_Refresh.setText("Limpiar Paquetes Recibidos");
        JButton_Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_RefreshMouseClicked(evt);
            }
        });
        jPanel1.add(JButton_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 190, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_images/FondoDif.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(910, 580));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 930, 570));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Consumir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consumir_ButtonActionPerformed

    }//GEN-LAST:event_Consumir_ButtonActionPerformed

    private void Consumir_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consumir_ButtonMouseClicked
        try {
            try (FileWriter paquetetxt = new FileWriter ("C:/Users/raulr/OneDrive/Escritorio/Paquetes/paquetesconsumidos.txt")) {
                paquetetxt.write(Mensajes_Cliente2.getText());
                JOptionPane.showMessageDialog(null, "Archivo .txt generado en la carpeta Paquetes");
                Mensajes_Cliente.append("Paquete Consumido y guardado en:");
                Mensajes_Cliente.append("C:/Users/raulr/OneDrive/Escritorio/Paquetes/paquetesconsumidos.txt");
                /*
                File archivo;
                FileOutputStream salida;
                String paquetetxt = String.valueOf(Mensajes_Cliente2);
                try {
                salida = new FileOutputStream(paquetetxt);
                byte[] byttxt=paquetetxt.getBytes();
                salida.write(byttxt);
                Mensajes_Cliente.append("Paquetes Consumidos");
                } catch (IOException e) {
                }*/
            }
        } catch (IOException ex) {
            Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Consumir_ButtonMouseClicked

    private void jButtonsocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsocketActionPerformed
       
    }//GEN-LAST:event_jButtonsocketActionPerformed
//Click socketsalir
    private void jButtonsocketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsocketMouseClicked
        JOptionPane.showMessageDialog(null, "Cliente cerrando socket .... termina la aplicacion..\nPresione Ok para cerrar ...");
        //Mensajes_Cliente.append("Cliente cerrando socket .... termina la aplicacion..");
            //Mensajes_Cliente.append("Cierre en 3,2,1 ...");
        try {
            Cliente.socket.close();
            //Thread.sleep(3000);
            System.exit(0);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButtonsocketMouseClicked

    private void JButton_RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_RefreshMouseClicked
        Mensajes_Cliente2.setText(null);
    }//GEN-LAST:event_JButton_RefreshMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente_Label;
    private javax.swing.JButton Consumir_Button;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton JButton_Refresh;
    private javax.swing.JTextArea Mensajes_Cliente;
    private javax.swing.JTextArea Mensajes_Cliente2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonsocket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void textoencaja(String mensaje) {
       Mensajes_Cliente.append(mensaje + "\n");
    }

    @Override
    public void setControlador(ControladorCliente controlador) {
        this.controlador = controlador;
    }

    @Override
    public void hacerVisible() {
         setVisible(true);
    }
/*
    @Override
    public void Consumir() {
        //Int_TxtField_S.setText(("Prueba"));
    }
   */
    public void textoencaja2(String mensaje) { 
       Mensajes_Cliente2.append(mensaje + "\n");
    }
}
