/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com_cliente_servidor.vistaS;


import com_cliente_servidor.controladorS.ControladorServidor;

import com.mysql.cj.xdevapi.Statement;
//import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.IOException;
import java.lang.String;
import java.util.Vector;

/**
 *
 * @author raulr
 */

public class ServidorFrame extends javax.swing.JFrame implements VistaS{
    ControladorServidor controlador;
    /**
     * Creates new form ServidorFrame
     */
    public ServidorFrame() {
        initComponents();


//  this.Paquetes.removeAllItems();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/comunicacion_servidor","root","");
            java.sql.Statement Sent = conexion.createStatement();
            ResultSet rs = Sent.executeQuery("select * from paquetes");
            while (rs.next()) {
                this.Paquetes.addItem(String.valueOf(rs.getInt("Paquete")));   
            }
        } catch (Exception e) {
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Int_Label = new javax.swing.JLabel();
        String_Label = new javax.swing.JLabel();
        Bool_Label = new javax.swing.JLabel();
        Byte_Label = new javax.swing.JLabel();
        Char_Label = new javax.swing.JLabel();
        Long_Label = new javax.swing.JLabel();
        Float_Label = new javax.swing.JLabel();
        Double_Label = new javax.swing.JLabel();
        Array_Label = new javax.swing.JLabel();
        String_TxtField_S = new javax.swing.JTextField();
        Int_TxtField_S = new javax.swing.JTextField();
        Bool_TxtField_S = new javax.swing.JTextField();
        Byte_TxtField_S = new javax.swing.JTextField();
        Char_TxtField_S = new javax.swing.JTextField();
        Long_TxtField_S = new javax.swing.JTextField();
        Float_TxtField_S = new javax.swing.JTextField();
        Double_TxtField_S = new javax.swing.JTextField();
        Array_TxtField_S = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensajes_Servidor = new javax.swing.JTextArea();
        Cliente_Label = new javax.swing.JLabel();
        Paquetes = new javax.swing.JComboBox<>();
        Enviar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Int_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Int_Label.setText("int");
        jPanel1.add(Int_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 60, 50));

        String_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        String_Label.setText("string");
        jPanel1.add(String_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 100, 50));

        Bool_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Bool_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bool_Label.setText("boolean");
        Bool_Label.setToolTipText("");
        Bool_Label.setMaximumSize(new java.awt.Dimension(90, 90));
        Bool_Label.setMinimumSize(new java.awt.Dimension(90, 90));
        Bool_Label.setPreferredSize(new java.awt.Dimension(90, 90));
        jPanel1.add(Bool_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 110, 50));

        Byte_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Byte_Label.setText("byte");
        jPanel1.add(Byte_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 80, -1));

        Char_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Char_Label.setText("char");
        jPanel1.add(Char_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 60, -1));

        Long_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Long_Label.setText("long");
        jPanel1.add(Long_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 100, 50));

        Float_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Float_Label.setText("float");
        jPanel1.add(Float_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 100, 50));

        Double_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Double_Label.setText("double");
        jPanel1.add(Double_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 100, 50));

        Array_Label.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Array_Label.setText("array");
        jPanel1.add(Array_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 100, 50));

        String_TxtField_S.setEditable(false);
        String_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        String_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        String_TxtField_S.setText(" ");
        String_TxtField_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String_TxtField_SActionPerformed(evt);
            }
        });
        jPanel1.add(String_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 170, 40));

        Int_TxtField_S.setEditable(false);
        Int_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Int_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Int_TxtField_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Int_TxtField_SActionPerformed(evt);
            }
        });
        jPanel1.add(Int_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 130, 40));

        Bool_TxtField_S.setEditable(false);
        Bool_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Bool_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bool_TxtField_S.setText(" ");
        Bool_TxtField_S.setToolTipText("");
        jPanel1.add(Bool_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 130, 40));

        Byte_TxtField_S.setEditable(false);
        Byte_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Byte_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Byte_TxtField_S.setText(" ");
        jPanel1.add(Byte_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 130, 40));

        Char_TxtField_S.setEditable(false);
        Char_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Char_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Char_TxtField_S.setText(" ");
        Char_TxtField_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Char_TxtField_SActionPerformed(evt);
            }
        });
        jPanel1.add(Char_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 130, 40));

        Long_TxtField_S.setEditable(false);
        Long_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Long_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Long_TxtField_S.setText(" ");
        jPanel1.add(Long_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 130, 40));

        Float_TxtField_S.setEditable(false);
        Float_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Float_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Float_TxtField_S.setToolTipText("");
        jPanel1.add(Float_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 130, 40));

        Double_TxtField_S.setEditable(false);
        Double_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Double_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Double_TxtField_S.setText(" ");
        Double_TxtField_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Double_TxtField_SActionPerformed(evt);
            }
        });
        jPanel1.add(Double_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 130, 40));

        Array_TxtField_S.setEditable(false);
        Array_TxtField_S.setBackground(new java.awt.Color(255, 255, 255));
        Array_TxtField_S.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Array_TxtField_S.setText(" ");
        Array_TxtField_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Array_TxtField_SActionPerformed(evt);
            }
        });
        jPanel1.add(Array_TxtField_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 170, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensajes_Servidor.setEditable(false);
        Mensajes_Servidor.setBackground(new java.awt.Color(204, 204, 204));
        Mensajes_Servidor.setColumns(20);
        Mensajes_Servidor.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Mensajes_Servidor.setRows(5);
        jScrollPane1.setViewportView(Mensajes_Servidor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 480, 360));

        Cliente_Label.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        Cliente_Label.setText("SERVIDOR");
        jPanel1.add(Cliente_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        Paquetes.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        Paquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquetes" }));
        Paquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaquetesActionPerformed(evt);
            }
        });
        jPanel1.add(Paquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 320, 50));

        Enviar.setBackground(new java.awt.Color(166, 117, 179));
        Enviar.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Enviar.setText("Enviar a Cliente");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 210, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com_images/FondoDif.png"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(910, 580));
        Fondo.setMinimumSize(new java.awt.Dimension(910, 580));
        Fondo.setPreferredSize(new java.awt.Dimension(910, 580));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void String_TxtField_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_String_TxtField_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_String_TxtField_SActionPerformed

    private void Array_TxtField_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Array_TxtField_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Array_TxtField_SActionPerformed

    private void Char_TxtField_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Char_TxtField_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Char_TxtField_SActionPerformed

    
    
//Combo BOX BD
    private void PaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaquetesActionPerformed

        try {
            java.sql.Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/comunicacion_servidor","root","");
            java.sql.Statement sent1 = con1.createStatement();
        //Rellenar Campos    
            java.sql.ResultSet rs1 = sent1.executeQuery("select * from paquetes where Paquete= '"+this.Paquetes.getSelectedItem()+"'");
            rs1.next();
            Int_TxtField_S.setText(String.valueOf(rs1.getInt("Tipo_Int")));
            Bool_TxtField_S.setText(String.valueOf(rs1.getBoolean("Tipo_Bool")));
            Byte_TxtField_S.setText(String.valueOf(rs1.getByte("Tipo_Byte")));
            Char_TxtField_S.setText(rs1.getNString("Tipo_Char"));
            Long_TxtField_S.setText(String.valueOf(rs1.getLong("Tipo_Long")));
            Float_TxtField_S.setText(String.valueOf(rs1.getFloat("Tipo_Float")));
            Double_TxtField_S.setText(String.valueOf(rs1.getDouble("Tipo_Double")));
            Array_TxtField_S.setText(rs1.getString("Tipo_Array"));
            String_TxtField_S.setText(rs1.getString("Tipo_String"));
          /*  if (con1 != null) {
                Mensajes_Cliente.showMessageDialog(null, "Conectado correctamente a la base de datos");
            }*/
        } catch (Exception e) {
        }    
    }//GEN-LAST:event_PaquetesActionPerformed

    private void Int_TxtField_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Int_TxtField_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Int_TxtField_SActionPerformed

    private void Double_TxtField_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Double_TxtField_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Double_TxtField_SActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Array_Label;
    private javax.swing.JTextField Array_TxtField_S;
    private javax.swing.JLabel Bool_Label;
    private javax.swing.JTextField Bool_TxtField_S;
    private javax.swing.JLabel Byte_Label;
    private javax.swing.JTextField Byte_TxtField_S;
    private javax.swing.JLabel Char_Label;
    private javax.swing.JTextField Char_TxtField_S;
    private javax.swing.JLabel Cliente_Label;
    private javax.swing.JLabel Double_Label;
    private javax.swing.JTextField Double_TxtField_S;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Float_Label;
    private javax.swing.JTextField Float_TxtField_S;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Int_Label;
    private javax.swing.JTextField Int_TxtField_S;
    private javax.swing.JLabel Long_Label;
    private javax.swing.JTextField Long_TxtField_S;
    private javax.swing.JTextArea Mensajes_Servidor;
    private javax.swing.JComboBox<String> Paquetes;
    private javax.swing.JLabel String_Label;
    private javax.swing.JTextField String_TxtField_S;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    

    @Override
    public void setControlador(ControladorServidor controlador) {
        this.controlador = controlador;
    }
    

    @Override
    public void textoencaja(String mensaje) {
       Mensajes_Servidor.append(mensaje + "\n");
    }

    @Override
    public void hacerVisible() {
        setVisible(true);
    }
    
    
    @Override
    public void inicializar() {
        Enviar.setActionCommand(ENVIAR);
        Enviar.addActionListener(controlador);
    }
    
    

    @Override
    public String getMensajeAEnviar_paquete(){
       Mensajes_Servidor.append("_______________________________________\n");
       Mensajes_Servidor.append("Enviando paquete -> "+(String) this.Paquetes.getSelectedItem()+" <- al cliente...\n");
        return (String) this.Paquetes.getSelectedItem();
    }
    
        @Override
    public String getMensajeAEnviar_int() {
        Mensajes_Servidor.append("Enviando el Int: "+(String)this.Int_TxtField_S.getText()+"\n");
        return Int_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_bool() {
        Mensajes_Servidor.append("Enviando el Bool: "+(String)this.Bool_TxtField_S.getText()+"\n");
       return Bool_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_byte() {
        Mensajes_Servidor.append("Enviando el Byte: "+(String)this.Byte_TxtField_S.getText()+"\n");
        return Byte_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_char() {
        Mensajes_Servidor.append("Enviando el Char: "+(String)this.Char_TxtField_S.getText()+"\n");
        return Char_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_long() {
        Mensajes_Servidor.append("Enviando el Long: "+(String)this.Long_TxtField_S.getText()+"\n");
       return Long_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_float() {
        Mensajes_Servidor.append("Enviando el Float: "+(String)this.Float_TxtField_S.getText()+"\n");
        return Float_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_double() {
        Mensajes_Servidor.append("Enviando el Double: "+(String)this.Double_TxtField_S.getText()+"\n");
        return Double_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_array() {
       Mensajes_Servidor.append("Enviando el Array: "+(String)this.Array_TxtField_S.getText()+"\n"); 
       return Array_TxtField_S.getText();
    }

    @Override
    public String getMensajeAEnviar_string() {
       Mensajes_Servidor.append("Enviando el String: "+(String)this.String_TxtField_S.getText()+"\n");
       Mensajes_Servidor.append("_______________________________________\n"); 
       return String_TxtField_S.getText();
    }    
 


}

    

